---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: {{ template "knative-operator.namespace" . }}
  labels:
    operator.knative.dev/release: devel
    app: {{ template "knative-operator.name" . }}-operator
    {{- include "knative-operator.labels" . | indent 4 }}
{{- if .Values.knativeOperator.config.logging }}
data:
  {{- toYaml .Values.knativeOperator.config.logging | nindent 2 }}
{{- else }}
data: {}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: {{ template "knative-operator.namespace" . }}
  labels:
    operator.knative.dev/release: devel
    app: {{ template "knative-operator.name" . }}-operator
    {{- include "knative-operator.labels" . | indent 4 }}
{{- if .Values.knativeOperator.config.observability }}
data:
  {{- toYaml .Values.knativeOperator.config.observability | nindent 2 }}
{{- else }}
data: {}
{{- end }}
