{{- if and .Values.knativeOperator.enabled .Values.knativeOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "knative-operator.serviceAccountName" . }}
  namespace: {{ template "knative-operator.namespace" . }}
  labels:
    app: {{ template "knative-operator.name" . }}-operator
    {{- include "knative-operator.labels" . | indent 4 }}
{{- end }}
