apiVersion: v1
appVersion: 7.6.2
description: Kibana ndjson resources uploader
keywords:
- odahu-flow
- logs
maintainers:
- name: ODAHU Team
  url: https://odahu.org
name: odahu-flow-kibana-loader
version: 0.0.1
