{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "odahu-flow-authorization.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- if .Values.opa.config.decisionLogsEnabled }}
    decision_logs:
      console: true
    {{- end }}
    plugins:
      envoy_ext_authz_grpc:
          addr: :9191
          query: data.odahu.allow
          dry-run: {{ .Values.opa.config.dryRun }}
          enable-reflection: true
  policy.rego: |
    {{- .Files.Get "files/openpolicyagent/policy.rego" | nindent 8 }}
{{- end }}