# Version of Fluentd
# By default .Chart.AppVersion version is used
# Type: string
# fluentdVersion: "1.0"

# Docker images registry
# This registry will be used for automatic docker image name deduction based on OdahuFlow naming for images
# Each image could be overridden manually in .<service>.image, please see .edi root section or other
# Type: string
imagesRegistry: odahu/

fluentd:

  resources:
    limits:
      memory: 200Mi
    requests:
      memory: 100Mi

  tolerations:
  - effect: NoSchedule
    operator: Exists

  # Extra annotations for the fluentd daemonSet pods
  #
  extraAnnotations: {}

  # Extra environment variables for the fluentd daemonSet pods
  # extraEnvs:
  # - name: FOO
  #   value: bar
  #
  extraEnvs: []

  # List of name-value pairs to be added to `{{ .Release.Name }}-secret` k8s Secret resource
  # extraSecrets:
  # - name: SECRET_VAR
  #   value: supersecret
  #
  extraSecrets: []

  # Common fluentd configuration
  # configData:
  #   fluent.conf: |
  #     @include source-config.inc
  #     @include filters-config.inc
  #     <match **>
  #       # Drop everything by default
  #       @type null
  #     </match>
  configData: {}

# List of secrets for accessing to image registry (if any)
# imagePullSecrets:
# - name: some-registry-secret
#
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: fluentd
