{{- if eq .Values.sync.target "s3" }}
{{- if eq .Values.sync.s3.authorization "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "syncer.helm-labels" (dict "component" "syncer" "root" .) | nindent 4 }}
type: Opaque
data:
  AWSKeyID: "{{ required "AWS Access Key ID is required for secret-based auth." .Values.sync.s3.AWSKeyID | b64enc }}"
  AWSSecretKey: "{{ required "AWS Secret Access Key is required for secret-based auth." .Values.sync.s3.AWSSecretKey | b64enc }}"
{{- end }}
{{- end }}
{{- if eq .Values.sync.target "azureblob" }}
{{- if eq .Values.sync.azureblob.authorization "accesskey" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "syncer.helm-labels" (dict "component" "syncer" "root" .) | nindent 4 }}
type: Opaque
data:
  AzureStorageAccount: "{{ required "Azure Storage Account Name" .Values.sync.azureblob.AzureStorageAccount | b64enc }}"
  AzureStorageAccessKey: "{{ required "Azure Storage Access Key (Primary or Secondary)" .Values.sync.azureblob.AzureStorageAccessKey | b64enc }}"
{{- end }}
{{- if eq .Values.sync.azureblob.authorization "sastoken" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "syncer.helm-labels" (dict "component" "syncer" "root" .) | nindent 4 }}
type: Opaque
data:
  AzureStorageAccount: "{{ required "Azure Storage Account Name" .Values.sync.azureblob.AzureStorageAccount | b64enc }}"
  AzureStorageSasToken: "{{ required "Azure Storage SAS Token" .Values.sync.azureblob.AzureStorageSasToken | b64enc }}"
{{- end }}
{{- end }}
