{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "odahu-flow-opa.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- if .Values.opa.config.decisionLogsEnabled }}
    decision_logs:
      console: true
    {{- end }}
    plugins:
      envoy_ext_authz_grpc:
          addr: :9191
          query: data.odahu.core.allow
          dry-run: {{ .Values.opa.config.dryRun }}
          enable-reflection: true
  {{- range $path, $content := .Files.Glob "policies/*.rego" }}
  {{ base $path }}: |
    {{ $content | toString | nindent 4 }}
  {{ end }}
  {{- range $key, $value := .Values.opa.policies}}
  {{- $key | nindent 2 }}: |
    {{- $value | b64dec | nindent 4 }}
  {{- end }}

{{- end }}