---
############################################################
# TLS certificate for OPA admission controller.
############################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odahu-flow-opa.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
---

############################################################
# Service to expose OPA admission controller (required by Kubernetes.)
############################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odahu-flow-opa.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      name: http
  selector:
    app.kubernetes.io/name: {{ include "odahu-flow-opa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-webhook-server
---
############################################################
# OPA admission controller deployment for injecting OPA-Istio.
############################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "odahu-flow-opa.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-webhook-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "odahu-flow-opa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-webhook-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "odahu-flow-opa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-webhook-server
      name: {{ .Release.Name }}-webhook-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: opa
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 443
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:443"
            - "/policies/inject.rego"
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: server-cert
            - readOnly: true
              mountPath: /policies
              name: inject-policy
      volumes:
        - name: inject-policy
          configMap:
            name: {{ .Release.Name }}-policy-inject
        - name: server-cert
          secret:
            secretName: {{ .Release.Name }}-webhook-server-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
############################################################
# OPA admission controller configuration.
############################################################
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-inject-policy
  labels:
    {{- include "odahu-flow-opa.labels" . | nindent 4 }}
webhooks:
  - name: istio.openpolicyagent.org
    clientConfig:
      service:
        name: {{ .Release.Name }}-webhook-server
        namespace: {{ .Release.Namespace }}
        path: "/v0/data/istio/inject"
      caBundle: {{ .Values.tls.ca }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchLabels:
        odahu-flow-authorization: enabled
    failurePolicy: Fail