{{- if .Values.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  workloadLabels:
    {{ .Values.authz.activationSelector }}: enabled
  filters:
    - insertPosition:
        index: BEFORE
        relativeTo: envoy.router
      listenerMatch:
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      filterType: HTTP
      filterName: "envoy.filters.http.jwt_authn"
      filterConfig:
        providers:
          oidc:
            issuer: {{ .Values.authn.oidcIssuer }}
            payload_in_metadata: jwt_payload
            # Forward a JWT to a service
            forward: true
            {{- if .Values.authn.localJwks }}
            local_jwks:
              inline_string: '{{ .Values.authn.localJwks }}'
            {{- else }}
            remote_jwks:
              http_uri:
                uri: {{ .Values.authn.oidcJwks }}
                cluster: outbound|{{ .Values.authn.oidcPort }}||{{ .Values.authn.oidcHost }}
                timeout:
                  seconds: 20
              cache_duration:
                seconds: 100
            {{- end }}
        rules:
          - match:
              prefix: /
            requires:
              {{- if .Values.authn.enabled }}
              provider_name: oidc
              {{- else }}
              allow_missing_or_failed: {}
              {{- end }}
    - insertPosition:
        index: BEFORE
        relativeTo: envoy.router
      listenerMatch:
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      filterType: HTTP
      filterName: "envoy.ext_authz"
      filterConfig:
        metadata_context_namespaces:
          - envoy.filters.http.jwt_authn
        grpc_service:
          timeout:
            seconds: 20
          google_grpc:
            {{- if .Values.authz.targetUri }}
            target_uri: {{ .Values.authz.targetUri }}
            {{- else }}
            target_uri: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:9191
            {{- end}}
            stat_prefix: "ext_authz"
{{- end }}