apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Release.Name }}
  namespace : {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.authn.oidcHost }}
  exportTo:
    - "*"
  location: MESH_EXTERNAL
  ports:
    - number: {{ .Values.authn.oidcPort }}
      name: https
      protocol: HTTPS
  resolution: DNS