kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
    {{- include "fluentd-daemonset.helm-labels" (dict "component" "fluentd-daemonset" "root" .) | nindent 4 }}
data:
  fluent.conf: |
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
    </filter>

    <match **>
      @type gcs
      auto_create_bucket false
      remove_tag_prefix kubernetes.var.log.container

      # Storing
      bucket {{ required "GCS bucket value is required" .Values.output.gcs.bucket }}
      object_key_format {{ .Values.output.objectKeyFormat | quote }}
      store_as {{ .Values.output.storeAs }}
      time_slice_wait {{ .Values.output.timeSliceWait }}
      utc

      path {{ .Values.output.path | quote }}
      time_slice_format {{ .Values.output.timeSliceFormat }}

      # Buffering
      <buffer hostname,tag,time>
        @type file
        path {{ .Values.output.buffering.path }}/kubernetes
        timekey {{ .Values.output.buffering.timekey }}
        timekey_wait {{ .Values.output.buffering.timekeyWait }}
        timekey_use_utc true
      </buffer>

      # Formatting
      <format>
        @type {{ .Values.output.format }}
      </format>
    </match>
