kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
    {{- include "fluentd-daemonset.helm-labels" (dict "component" "fluentd-daemonset" "root" .) | nindent 4 }}
data:
{{- range $path, $config := .Values.fluentd.configData }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end }}
