apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "fluentd-daemonset.helm-labels" (dict "component" "fluentd-daemonset" "root" .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fluentd-daemonset.helm-labels-for-search" (dict "component" "fluentd-daemonset" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fluentd-daemonset.helm-labels" (dict "component" "fluentd-daemonset" "root" .) | nindent 8 }}
      {{- if and (eq .Values.output.target "s3") (eq .Values.output.s3.authorization "iam" ) }}
      annotations:
        sidecar.istio.io/inject: "false"
        iam.amazonaws.com/role: {{ .Values.output.s3.customIAMRole }}
      {{- end }}
      {{- if and (eq .Values.output.target "gcs") (eq .Values.output.gcs.authorization "sa" ) }}
      annotations:
        accounts.google.com/service-account: {{ ternary .Values.output.gcs.customSA "default" (hasKey .Values.output.gcs "customSA") }}
        accounts.google.com/scopes: "https://www.googleapis.com/auth/devstorage.read_write"
      {{- end }}
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
      - name: fluentd
        command: ["fluentd"]
        args: ["-c", "/opt/fluent-config/fluent.conf"]
        image: "{{ include "fluentd.image-name" (dict "root" . "service" .Values.fluentd "tpl" "%sodahu-flow-fluentd:%s") }}"
        resources:
          {{- toYaml .Values.fluentd.resources | nindent 10 }}
        env:
        - name: FLUENTD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if eq .Values.output.target "azureblob" }}
        {{- if eq .Values.output.azureblob.authorization "sastoken" }}
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-secret"
              key: AzureStorageAccount
        - name: AZURE_STORAGE_SAS_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-secret"
              key: AzureStorageSasToken
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: fluentd-config
          mountPath: /opt/fluent-config
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-config
        configMap:
          name: "{{ .Release.Name }}-config"

