{{- if eq .Values.output.target "azureblob" }}
{{- if eq .Values.output.azureblob.authorization "sastoken" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "fluentd-daemonset.helm-labels" (dict "component" "fluentd-daemonset" "root" .) | nindent 4 }}
type: Opaque
data:
  AzureStorageAccount: "{{ required "Azure Storage Account Name" .Values.output.azureblob.AzureStorageAccount | b64enc }}"
  AzureStorageSasToken: "{{ required "Azure Storage SAS Token" .Values.output.azureblob.AzureStorageSasToken | b64enc }}"
{{- end }}
{{- end }}

