apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        {{- if .Values.kibanaData }}
        - name: kibana-import-data
          configMap:
            name: {{ .Release.Name }}-data
        {{- end }}
        - name: kibana-import-script
          configMap:
            name: {{ .Release.Name }}-script
            defaultMode: 0777
      containers:
      - name: {{ .Release.Name }}
        env:
        - name: KIBANA_URL
          value: {{ .Values.kibanaUrl }}
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources: {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: kibana-import-script
          mountPath: /opt/bin/import.sh
          subPath: import.sh
{{- range $path, $config := .Values.kibanaData }}
        - name: kibana-import-data
          mountPath: /opt/kibana-import-data/{{ $path }}
          subPath: {{ $path }}
{{- end }}
        command:
        - /opt/bin/import.sh
